
import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  english: {
    // Header
    'header.settings': 'Settings',
    'header.logout': 'Logout',
    
    // Dashboard
    'dashboard.title': 'Study Management Dashboard',
    'dashboard.protocol': 'Protocol: PROTO-2024-001 | Site: Metro General Hospital',
    'dashboard.participants.enrolled': 'Participants enrolled',
    'dashboard.pending.reviews': 'Pending reviews',
    'dashboard.adverse.events': 'Adverse events',
    'dashboard.upcoming.visits': 'Upcoming visits',
    'dashboard.next.events': 'Next 3 Study Events',
    'dashboard.study.management': 'Study Management',
    'dashboard.participant.list': 'Participant List',
    'dashboard.manage.calendar': 'Calendar',
    'dashboard.questionnaires': 'Questionnaires',
    'dashboard.export.questionnaires': 'Export Questionnaires',
    'dashboard.study.progress': 'Study Progress',
    'dashboard.diary.compliance': 'Diary Compliance',
    'dashboard.visit.compliance': 'Visit Compliance',
    'dashboard.enrollment': 'Enrollment',
    'dashboard.daily.diaries': 'Daily Diaries',
    'dashboard.site.visits': 'Visits',
    'dashboard.barcode.scanner': 'Barcode Scanner',
    'dashboard.fhir.interoperability': 'FHIR Interoperability',
    
    // Participant Management
    'participant.management': 'Participant Management',
    'participant.search': 'Search by patient ID or token...',
    'participant.of': 'of',
    'participant.participants': 'participants',
    'participant.patient.id': 'Patient ID',
    'participant.enrollment': 'Enrollment',
    'participant.visit.status': 'Visit Status',
    'participant.compliance': 'Compliance',
    'participant.next.visit': 'Next Visit',
    'participant.actions': 'Actions',
    'participant.view.details': 'View Details',
    'participant.view.questionnaires': 'View Questionnaires',
    'participant.schedule.visit': 'Schedule Visit',
    'participant.barcode.click': 'Click to view barcode',
    
    // Participant Details
    'details.title': 'Participant Details',
    'details.alerts': 'Alerts',
    'details.visit.overdue': 'Visit overdue',
    'details.monthly.assessment': 'Due for monthly assessment',
    'details.basic.info': 'Basic Information',
    'details.demographics': 'Demographics',
    'details.icf.title': 'Informed Consent (ICF)',
    'details.icf.version': 'ICF Version',
    'details.icf.signed.date': 'Signed Date',
    'details.icf.status': 'Status',
    'details.icf.action.required': 'Action Required',
    'details.icf.updated.schedule': 'ICF has been updated to v2.1. Please schedule re-consent visit.',
    
    // Participant specific
    'participant.profile': 'Profile',
    'participant.your.schedule': 'Your Schedule',
    'participant.days.remaining': 'days remaining',
    'participant.token': 'Participant Token',
    
    // Questionnaires
    'questionnaire.daily.symptom': 'Daily Symptom Diary',
    
    // Contact Information
    'contact.info': 'Contact',
    'contact.site.staff': 'Site Staff',
    'contact.principal.investigator': 'Principal Investigator',
    'contact.study.coordinator': 'Study Coordinator',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.emergency': 'Emergency Contact',
    'contact.emergency.info': 'Available 24/7 for urgent study-related matters',
    'contact.regulatory.authorities': 'Regulatory Authorities',
    'contact.safety.reporting': 'Safety Reporting',
    'contact.safety.note': 'Important',
    'contact.safety.description': 'Report any adverse events immediately to your study team',
    'contact.sponsor': 'Study Sponsor',
    'contact.company': 'Company',
    'contact.medical.monitor': 'Medical Monitor',
    'contact.unblinding.emergency': 'Emergency Unblinding',
    'contact.issued': 'Issued',
    'contact.tap.for.details': 'Tap for details',
    'contact.token.description': 'Click to view your participant profile and barcode details',
    
    // Activities
    'activity.weekly.survey': 'Weekly Survey',
    'activity.weekly.survey.details': 'Quick 5-minute questionnaire about your daily symptoms and medication adherence',
    'activity.online.location': 'Online - Complete from home',
    'activity.site.visit.blood': 'Site Visit - Blood Draw',
    'activity.site.visit.blood.details': 'Routine blood analysis for safety monitoring and efficacy evaluation',
    'activity.hospital.location': 'Metro General Hospital - Laboratory Building, 2nd Floor',
    'activity.site.visit.notes': 'Please fast for 12 hours before the visit. Bring your medication diary and any questions you may have.',
    'activity.daily.diary': 'Daily Health Diary',
    'activity.anytime': 'Anytime',
    'activity.daily.diary.details': 'Record your daily symptoms, medications taken, and any side effects',
    'activity.mobile.location': 'Online - Mobile app or web portal',
    'activity.survey.completed': 'Survey completed successfully! Thank you for your participation.',
    'activity.pdf.export': 'PDF export initiated - questionnaire responses would be downloaded as a secure, de-identified document.',
    'activity.view.details': 'Ver Detalles',
    'activity.important.notes': 'Important Notes',
    
    // Calendar
    'calendar.view.full': 'View Full Calendar',
    
    // Questionnaires
    'questionnaire.your.surveys': 'Your Questionnaires',
    'questionnaire.view.all': 'View All Questionnaires',
    'questionnaire.pending': 'Pending',
    'questionnaire.completed': 'Completed',
    'questionnaire.completion.rate': 'Completion Rate',
    'questionnaire.thanks.completing': 'Thank you for completing today\'s questionnaire!',
    'questionnaire.quick.survey': 'Quick 5-minute survey about your daily symptoms',
    'questionnaire.complete.now': 'Complete Now',
    
    // Questionnaire Form
    'questionnaire.form.question': 'Question',
    'questionnaire.form.of': 'of',
    'questionnaire.form.complete': 'Complete',
    'questionnaire.form.completed': 'Questionnaire Completed!',
    'questionnaire.form.thank.you': 'Thank you for completing',
    'questionnaire.form.responses.saved': 'Your responses have been saved.',
    'questionnaire.form.close': 'Close',
    'questionnaire.form.previous': 'Previous',
    'questionnaire.form.next': 'Next',
    'questionnaire.form.enter.response': 'Enter your response...',
    'questionnaire.form.not.at.all': 'Not at all',
    'questionnaire.form.extremely': 'Extremely',
    'questionnaire.form.selected': 'Selected',
    
    // Questionnaire List
    'questionnaire.list.title': 'Questionnaires',
    'questionnaire.list.completed.count': 'Completed',
    'questionnaire.list.in.progress.count': 'In Progress',
    'questionnaire.list.pending.count': 'Pending',
    'questionnaire.list.overdue.count': 'Overdue',
    'questionnaire.list.due.date': 'Due Date',
    'questionnaire.list.completed.date': 'Completed',
    'questionnaire.list.score': 'Score',
    'questionnaire.list.progress': 'Progress',
    'questionnaire.list.view.responses': 'View Responses',
    'questionnaire.list.no.responses': 'No responses recorded yet.',
    'questionnaire.list.responses.for': 'Responses for',
    'questionnaire.list.data.privacy': 'Data Privacy',
    'questionnaire.list.privacy.note': 'All questionnaire responses are encrypted and stored securely. Access is limited to authorized study personnel and complies with HIPAA regulations.',
    
    // Questionnaire Status
    'questionnaire.status.completed': 'Completed',
    'questionnaire.status.in.progress': 'In Progress', 
    'questionnaire.status.pending': 'Pending',
    'questionnaire.status.overdue': 'Overdue',
    
    // Sample Questionnaires
    'questionnaire.daily.symptom.diary': 'Daily Symptom Diary',
    'questionnaire.weekly.qol.assessment': 'Weekly Quality of Life Assessment',
    'questionnaire.medication.adherence': 'Medication Adherence Survey',
    'questionnaire.monthly.health': 'Monthly Health Survey',
    'questionnaire.side.effects': 'Side Effects Assessment',
    
    // Questionnaire Questions
    'questionnaire.question.symptoms.today': 'Which symptoms did you experience today?',
    'questionnaire.question.symptom.severity': 'On a scale of 1-10, how would you rate your overall symptom severity today?',
    'questionnaire.question.medication.taken': 'Did you take your study medication today?',
    'questionnaire.question.physical.health': 'How would you rate your physical health this week?',
    'questionnaire.question.emotional.wellbeing': 'How would you rate your emotional well-being this week?',
    'questionnaire.question.daily.activities': 'How much did health problems limit your daily activities?',
    'questionnaire.question.sleep.quality': 'How would you rate your sleep quality this week?',
    'questionnaire.question.doses.missed': 'How many doses did you miss this week?',
    'questionnaire.question.reasons.missed': 'If you missed doses, what were the reasons?',
    'questionnaire.question.overall.health': 'How would you rate your overall health?',
    
    // Questionnaire Options
    'questionnaire.option.headache': 'Headache',
    'questionnaire.option.nausea': 'Nausea',
    'questionnaire.option.fatigue': 'Fatigue',
    'questionnaire.option.dizziness': 'Dizziness',
    'questionnaire.option.loss.appetite': 'Loss of appetite',
    'questionnaire.option.none': 'None',
    'questionnaire.option.yes.prescribed': 'Yes, as prescribed',
    'questionnaire.option.yes.missed.dose': 'Yes, but missed a dose',
    'questionnaire.option.no.forgot': 'No, forgot',
    'questionnaire.option.no.side.effects': 'No, side effects',
    'questionnaire.option.not.at.all': 'Not at all',
    'questionnaire.option.little.bit': 'A little bit',
    'questionnaire.option.moderately': 'Moderately',
    'questionnaire.option.quite.bit': 'Quite a bit',
    'questionnaire.option.extremely': 'Extremely',
    'questionnaire.option.forgot': 'Forgot',
    'questionnaire.option.side.effects': 'Side effects',
    'questionnaire.option.felt.better': 'Felt better',
    'questionnaire.option.too.busy': 'Too busy',
    'questionnaire.option.cost': 'Cost',
    'questionnaire.option.other': 'Other',
    
    // eConsent Signature
    'econsent.signature.canvas.instruction': 'Please sign in the box below',
    'econsent.signature.clear.confirm': 'Are you sure you want to clear your signature?',
    'econsent.signature.invalid': 'Please provide a valid signature',
    'econsent.signature.success': 'Document signed successfully',
    'econsent.signature.error': 'Error signing document. Please try again.',
    'econsent.previous.signed': 'Previous Signed ICFs',
    'econsent.optional.available': 'Optional ICFs Available',
    'econsent.audio.playback': 'Audio Playback Controls',
    'econsent.pharmacokinetics': 'Pharmacokinetics (PK)',
    'econsent.biomarkers': 'Biomarkers',
    'econsent.pregnant.partner': 'Pregnant Partner',
    'econsent.last.updated': 'Last Updated',
    'econsent.version': 'Version',
    'econsent.sign.button': 'Sign',
    'econsent.playback.speed': 'Playback Speed',
    'econsent.normal.speed': 'Normal',
    'econsent.slow.speed': 'Slow',
    'econsent.fast.speed': 'Fast',
    
    // Visits
    'visits.site.visits': 'Visits',
    'visits.baseline.completed': 'Baseline Visit - Completed',
    'visits.baseline.procedures': 'Blood draw, vital signs, questionnaires completed',
    'visits.notes': 'Visit Notes',
    'visits.baseline.notes': 'All procedures completed successfully. Blood pressure slightly elevated, will monitor at next visit. Patient reported no adverse events.',
    'visits.week4.scheduled': 'Week 4 Visit - Scheduled',
    'visits.week4.procedures': 'Blood draw, safety evaluation, questionnaires',
    'visits.preparation.notes': 'Preparation Notes',
    'visits.week4.notes': 'Please fast for 12 hours before the visit. Bring your medication diary and any questions you may have.',
    
    // Profile
    'profile.view.settings': 'View Profile & Settings',
    'profile.export.pdf': 'Export My Responses (PDF)',
    'profile.privacy.security': 'Privacy & Security',
    'profile.privacy.description': 'Your data is encrypted and protected according to HIPAA standards. All responses are de-identified for analysis.',
    'details.study.progress': 'Study Progress',
    'details.recent.activity': 'Recent Activity',
    'details.upcoming.events': 'Upcoming Events',
    'details.age': 'Age',
    'details.gender': 'Gender',
    'details.ethnicity': 'Ethnicity',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your preferences and account',
    'settings.back': 'Back',
    'settings.language.preferences': 'Language Preferences',
    'settings.display.language': 'Display Language',
    'settings.language.note': 'Changes will be applied after refreshing the page',
    'settings.tutorial.section': 'Tutorial',
    'settings.start.tutorial': 'Start Tutorial',
    'settings.tutorial.description': 'Learn how to use the application with guided tours',
    'settings.account.actions': 'Account Actions',
    'settings.sign.out': 'Sign Out',
    'settings.sign.out.note': 'You will be redirected to the login page',
    
    // Onboarding
    'onboarding.action.required': 'Action Required',
    'onboarding.previous': 'Previous',
    'onboarding.next': 'Next',
    'onboarding.skip': 'Skip Tutorial',
    'onboarding.try.it': 'Try It',
    'onboarding.finish': 'Finish',
    
    // Participant Onboarding
    'onboarding.participant.welcome.title': 'Welcome to Your Study Portal',
    'onboarding.participant.welcome.description': 'This is your personal dashboard where you can track your study progress and completion status.',
    'onboarding.participant.progress.title': 'Study Progress Tracker',
    'onboarding.participant.progress.description': 'Monitor your overall study completion percentage and days remaining in the study.',
    'onboarding.participant.schedule.title': 'Your Schedule',
    'onboarding.participant.schedule.description': 'View upcoming appointments, questionnaires, and site visits. Click to explore your calendar.',
    'onboarding.participant.schedule.action': 'Click on the Schedule tab to see your upcoming activities',
    'onboarding.participant.questionnaires.title': 'Questionnaires',
    'onboarding.participant.questionnaires.description': 'Complete required surveys and track your response completion rate.',
    'onboarding.participant.questionnaires.action': 'Click on Questionnaires to see pending surveys',
    'onboarding.participant.econsent.title': 'Electronic Consent',
    'onboarding.participant.econsent.description': 'Review and manage your informed consent documents and signatures.',
    'onboarding.participant.visits.title': 'Site Visits',
    'onboarding.participant.visits.description': 'Track your completed and upcoming site visits with detailed information.',
    'onboarding.participant.contact.title': 'Contact Information',
    'onboarding.participant.contact.description': 'Access contact details for your study team, emergency contacts, and important numbers.',
    
    // Investigator Onboarding
    'onboarding.investigator.metrics.title': 'Study Metrics Overview',
    'onboarding.investigator.metrics.description': 'Monitor key study metrics including enrolled participants, pending reviews, and adverse events.',
    'onboarding.investigator.participants.title': 'Participant Management',
    'onboarding.investigator.participants.description': 'Access comprehensive participant list with enrollment status, compliance, and visit schedules.',
    'onboarding.investigator.calendar.title': 'Calendar Management',
    'onboarding.investigator.calendar.description': 'Schedule and manage participant visits, appointments, and study milestones.',
    'onboarding.investigator.barcode.title': 'Barcode Scanner',
    'onboarding.investigator.barcode.description': 'Quickly identify participants and access their information using barcode scanning.',
    'onboarding.investigator.fhir.title': 'FHIR Interoperability',
    'onboarding.investigator.fhir.description': 'Export study data in FHIR format for integration with healthcare systems.',
    'onboarding.investigator.progress.title': 'Compliance Tracking',
    'onboarding.investigator.progress.description': 'Monitor study progress, diary compliance, and visit completion rates.',
    
    // CRO/Sponsor Onboarding
    'onboarding.cro.overview.title': 'Portfolio Overview',
    'onboarding.cro.overview.description': 'Get a high-level view of all active studies, research sites, and participant metrics.',
    'onboarding.cro.selector.title': 'Study Selection',
    'onboarding.cro.selector.description': 'Choose which study to focus on for detailed analysis and management.',
    'onboarding.cro.tabs.title': 'Main Navigation',
    'onboarding.cro.tabs.description': 'Access different sections: study details, questionnaires, schedules, participants, and reports.',
    'onboarding.cro.questionnaires.title': 'Questionnaire Analytics',
    'onboarding.cro.questionnaires.description': 'Analyze response rates, quality reviews, and data validation across all sites.',
    'onboarding.cro.questionnaires.action': 'Click on Questionnaires to explore analytics',
    'onboarding.cro.reports.title': 'Reports & Downloads',
    'onboarding.cro.reports.description': 'Generate and download various reports for regulatory submissions and analysis.',
    'onboarding.cro.reports.action': 'Click on Reports to see available downloads',
    
    // eConsent
    'econsent.title': 'Consent',
    'econsent.subtitle': 'Review and sign your informed consent document',
    'econsent.document.title': 'Informed Consent Form',
    'econsent.audio.play': 'Play Audio',
    'econsent.audio.pause': 'Pause Audio',
    'econsent.audio.stop': 'Stop Audio',
    'econsent.search.placeholder': 'Search in document...',
    'econsent.search.results': 'Search Results',
    'econsent.search.no.results': 'No results found',
    'econsent.signature.required': 'Electronic Signature Required',
    'econsent.signature.full.name': 'Full Name',
    'econsent.signature.date': 'Date',
    'econsent.signature.agree': 'I agree to participate in this study',
    'econsent.signature.sign': 'Sign Document',

    // Consent Dashboard
    'consent.dashboard.title': 'Consent Management',
    'consent.dashboard.pending': 'Pending Signatures',
    'consent.dashboard.urgent': 'Urgent',
    'consent.dashboard.high.priority': 'High Priority',
    'consent.dashboard.normal': 'Normal',
    'consent.dashboard.avg.days': 'Avg Days Pending',
    'consent.dashboard.search.placeholder': 'Search participants or subject IDs...',
    'consent.dashboard.no.results': 'No matching signatures found',
    'consent.dashboard.no.pending': 'No pending signatures',
    'consent.dashboard.signed.on': 'Signed on',
    'consent.dashboard.days.pending': 'days pending',
    'consent.dashboard.view': 'View',
    'consent.dashboard.sign': 'Sign',
    'consent.dashboard.reauth.title': 'Re-authenticate to Sign Consent',
    'consent.dashboard.reauth.description': 'For security and compliance purposes, please re-enter your password to electronically sign this consent form.',

    // Consent Types
    'consent.type.main.icf': 'Main Informed Consent',
    'consent.type.pharmacokinetics': 'Pharmacokinetics Study',
    'consent.type.biomarkers': 'Biomarker Analysis',
    'consent.type.pregnant.partner': 'Pregnant Partner Consent',

    // Credential Verification
    'credential.verification.title': 'Re-authenticate to Sign',
    'credential.verification.description': 'For security and compliance purposes, please re-enter your password.',
    'credential.verification.password.label': 'Password',
    'credential.verification.password.placeholder': 'Enter your password',
    'credential.verification.password.required': 'Password is required',
    'credential.verification.invalid.password': 'Invalid password',
    'credential.verification.error': 'Authentication failed',
    'credential.verification.verify': 'Verify',
    'credential.verification.verifying': 'Verifying...',
    'econsent.signature.clear': 'Clear Signature',
    'econsent.signature.complete': 'Consent Signed Successfully',
    'econsent.download.pdf': 'Download PDF',
    'econsent.view.signed': 'View Signed Document',
    'econsent.history': 'History',
    'econsent.status.signed': 'Signed',
    'econsent.status.superseded': 'Superseded',
    'econsent.status.pending': 'Pending',
    
    // Common
    'common.welcome': 'Welcome',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.continue': 'Continue',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.complete': 'Complete',
    'common.completed': 'Completed',
    'common.due.today': 'Due Today',
    'common.pending': 'Pending',
    'common.details': 'Details',
    'common.milestone': 'Milestone',
    'common.regulatory': 'Regulatory',
    
    // Login and Authentication
    'login.title': 'Sign In',
    'login.subtitle': 'Sign in to access your account',
    'login.email': 'Email',
    'login.email.placeholder': 'Enter your email',
    'login.password': 'Password',
    'login.password.placeholder': 'Enter your password',
    'login.role.select': 'Select your role',
    'login.role.selection.subtitle': 'Select your role to continue',
    'login.button': 'Sign In',
    'login.back': 'Back to Role Selection',
    'login.help': "Don't have access? Contact your administrator",
    'login.roles.participant': 'Participant',
    'login.roles.investigator': 'Site',
    'login.roles.cro-sponsor': 'Sponsor/CRO',
    'login.roles.participant.description': 'Access your study participation portal',
    'login.roles.investigator.description': 'Manage and monitor clinical studies',
    'login.roles.cro-sponsor.description': 'Oversee and administer research programs',
    
    // Status values
    'status.completed': 'completed',
    'status.scheduled': 'scheduled',
    'status.overdue': 'overdue',
    
    // Activity types
    'activity.visit': 'visit',
    'activity.questionnaire': 'questionnaire',
    'activity.call': 'call',
    'activity.diary': 'diary',
    'activity.assessment': 'assessment',
    'activity.lab': 'lab work',
    'activity.meeting': 'meeting',
    
    // Study Selector
    'study.selector.investigator.title': 'Select Study - Site Investigator',
    'study.selector.cro.title': 'Select Study - CRO/Sponsor',
    'study.selector.subtitle': 'Choose the study you want to access',
    'study.sites': 'sites',
    'study.participants': 'participants',
    
    // CRO/Sponsor Dashboard
    'cro.portfolio.overview': 'Portfolio Overview',
    'cro.global.research.ops': 'Global Research Operations Dashboard',
    'cro.active.studies': 'Active studies',
    'cro.research.sites': 'Research sites',
    'cro.total.participants': 'Total participants',
    'cro.compliance.rate': 'Compliance rate',
    'cro.study.details': 'Study Details',
    'cro.questionnaires': 'Questionnaires',
    'cro.schedule': 'Schedule',
    'cro.participants': 'Participants',
    'cro.reports': 'Reports',
    'cro.select.study': 'Select a Study',
    'cro.performance.metrics': 'Performance Metrics',
    'cro.budget.utilization': 'Budget Utilization',
    'cro.timeline.progress': 'Timeline Progress',
    'cro.spent': 'Spent',
    'cro.completion': 'Completion',
    'cro.enrollment.tracker': 'Enrollment Tracker',
    'cro.current': 'Current',
    'cro.target': 'Target',
    'cro.retention.rate': 'Retention Rate',
    'cro.compliance.score': 'Compliance Score',
    'cro.set.favorite': 'Set as Favorite',
    'cro.remove.favorite': 'Remove Favorite',
    'cro.favorite.study': 'Favorite Study',
    'cro.milestone.schedule': 'Study Milestones & Schedule',
    'cro.key.milestones': 'Key Study Milestones',
    'cro.milestone.completed': 'Completed',
    'cro.milestone.pending': 'Pending',
    'cro.questionnaire.analytics': 'Questionnaire Analytics',
    'cro.response.rates': 'Response Rates',
    'cro.quality.reviews': 'Quality Reviews',
    'cro.data.validation': 'Data Validation Issues',
    'cro.daily.symptom': 'Daily Symptom',
    'cro.weekly.qol': 'Weekly QoL',
    'cro.monthly.health': 'Monthly Health',
    'cro.download.reports': 'Download Reports',
    'cro.site.users.report': 'Site Users Report',
    'cro.site.users.report.description': 'Detailed site investigator and staff activity report',
    'cro.questionnaire.report': 'Questionnaire Report', 
    'cro.questionnaire.report.description': 'Complete questionnaire responses and compliance data',
    'cro.milestones.report': 'Milestones Report',
    'cro.milestones.report.description': 'Timeline tracking and milestone achievement analysis',
    'cro.interoperability': 'Interoperability Module',
    'cro.export.fhir': 'Export FHIR Data',
    'cro.export.fhir.description': 'Export study data in FHIR R4 format for regulatory submission',
    'cro.export.hl7': 'Export HL7 Messages',
    'cro.export.hl7.description': 'Generate HL7 messages for healthcare system integration', 
    'cro.validate.cdisc': 'Validate CDISC Standards',
    'cro.validate.cdisc.description': 'Validate against CDISC Study Data Tabulation Model',
    'cro.advanced.analytics': 'Advanced Analytics',
    
    // Study Details Attributes
    'study.protocol': 'Protocol',
    'study.phase': 'Phase',
    'study.sponsor': 'Sponsor',
    'study.sites.count': 'Sites',
    'study.participants.count': 'Participants',
    'study.status': 'Status',
    'study.recent.alerts': 'Recent Alerts',
    
    // ClinicalTrials.gov Status Values
    'study.status.not.yet.recruiting': 'Not yet recruiting',
    'study.status.recruiting': 'Recruiting',
    'study.status.enrolling.by.invitation': 'Enrolling by invitation',
    'study.status.active.not.recruiting': 'Active, not recruiting',
    'study.status.suspended': 'Suspended',
    'study.status.terminated': 'Terminated',
    'study.status.completed': 'Completed',
    'study.status.withdrawn': 'Withdrawn',
    'study.status.unknown': 'Unknown status',
    
    // Recruitment and Site Metrics
    'study.recruitment.metrics': 'Recruitment Metrics',
    'study.site.metrics': 'Site Opening Metrics',
    'study.recruitment.rate': 'Recruitment Rate',
    'study.patients.per.month': 'patients/month',
    'study.sites.opened': 'Sites Opened',
    'study.sites.planned': 'Sites Planned',
    'study.site.activation.rate': 'Site Activation Rate',
    'study.days.to.activate': 'days to activate',
    
    // Alert Messages
    'alert.cardiology.milestone': 'Cardiology milestone achieved ahead of schedule',
    'alert.interim.analysis': 'PARADIGM-CV interim analysis completed',
    'alert.enrollment.target': 'Enrollment target reached for Q4',
    'alert.safety.review': 'Monthly safety review completed',
    'alert.site.activation': 'New site activated in Boston Medical Center',
    'alert.data.validation': 'Data validation issues resolved',
    'alert.regulatory.submission': 'Regulatory submission prepared',
    'alert.biomarker.analysis': 'Biomarker analysis milestone completed'
  },
  spanish: {
    // Header
    'header.settings': 'Configuración',
    'header.logout': 'Cerrar Sesión',
    
    // Dashboard
    'dashboard.title': 'Panel de Gestión del Estudio',
    'dashboard.protocol': 'Protocolo: PROTO-2024-001 | Sitio: Hospital General Metro',
    'dashboard.participants.enrolled': 'Participantes inscritos',
    'dashboard.pending.reviews': 'Revisiones pendientes',
    'dashboard.adverse.events': 'Eventos adversos',
    'dashboard.upcoming.visits': 'Visitas próximas',
    'dashboard.next.events': 'Próximos 3 Eventos del Estudio',
    'dashboard.study.management': 'Gestión del Estudio',
    'dashboard.participant.list': 'Lista de Participantes',
    'dashboard.manage.calendar': 'Calendario',
    'dashboard.questionnaires': 'Cuestionarios',
    'dashboard.export.questionnaires': 'Exportar Cuestionarios',
    'dashboard.study.progress': 'Progreso del Estudio',
    'dashboard.diary.compliance': 'Cumplimiento del Diario',
    'dashboard.visit.compliance': 'Cumplimiento de Visitas',
    'dashboard.enrollment': 'Inscripción',
    'dashboard.daily.diaries': 'Diarios Diarios',
    'dashboard.site.visits': 'Visitas',
    'dashboard.barcode.scanner': 'Escáner de Códigos de Barras',
    'dashboard.fhir.interoperability': 'Interoperabilidad FHIR',
    
    // Participant Management
    'participant.management': 'Gestión de Participantes',
    'participant.search': 'Buscar por ID de paciente o token...',
    'participant.of': 'de',
    'participant.participants': 'participantes',
    'participant.patient.id': 'ID del Paciente',
    'participant.enrollment': 'Inscripción',
    'participant.visit.status': 'Estado de Visita',
    'participant.compliance': 'Cumplimiento',
    'participant.next.visit': 'Próxima Visita',
    'participant.actions': 'Acciones',
    'participant.view.details': 'Ver Detalles',
    'participant.view.questionnaires': 'Ver Cuestionarios',
    'participant.schedule.visit': 'Programar Visita',
    'participant.barcode.click': 'Haga clic para ver el código de barras',
    'participant.profile': 'Perfil',
    'participant.your.schedule': 'Tu Agenda',
    'participant.days.remaining': 'días restantes',
    'participant.token': 'Token de Participante',
    
    // Questionnaires
    'questionnaire.daily.symptom': 'Diario de Síntomas Diarios',
    
    // Contact Information
    'contact.info': 'Contacto',
    'contact.site.staff': 'Personal del Sitio',
    'contact.principal.investigator': 'Investigador Principal',
    'contact.study.coordinator': 'Coordinador del Estudio',
    'contact.phone': 'Teléfono',
    'contact.email': 'Correo Electrónico',
    'contact.emergency': 'Contacto de Emergencia',
    'contact.emergency.info': 'Disponible 24/7 para asuntos urgentes relacionados con el estudio',
    'contact.regulatory.authorities': 'Autoridades Regulatorias',
    'contact.safety.reporting': 'Reporte de Seguridad',
    'contact.safety.note': 'Importante',
    'contact.safety.description': 'Reporte cualquier evento adverso inmediatamente a su equipo de estudio',
    'contact.sponsor': 'Patrocinador del Estudio',
    'contact.company': 'Empresa',
    'contact.medical.monitor': 'Monitor Médico',
    'contact.unblinding.emergency': 'Desenmascaramiento de Emergencia',
    'contact.issued': 'Emitido',
    'contact.tap.for.details': 'Toca para ver detalles',
    'contact.token.description': 'Haz clic para ver tu perfil de participante y detalles del código de barras',
    
    // Activities  
    'activity.weekly.survey': 'Cuestionario Semanal',
    'activity.weekly.survey.details': 'Cuestionario rápido de 5 minutos sobre sus síntomas diarios y adherencia a la medicación',
    'activity.online.location': 'En línea - Complete desde casa',
    'activity.site.visit.blood': 'Visita al Sitio - Extracción de Sangre',
    'activity.site.visit.blood.details': 'Análisis de sangre de rutina para monitoreo de seguridad y evaluación de eficacia',
    'activity.hospital.location': 'Hospital General Metro - Edificio de Laboratorio, 2do Piso',
    'activity.site.visit.notes': 'Por favor ayune durante 12 horas antes de la visita. Traiga su diario de medicamentos y cualquier pregunta que pueda tener.',
    'activity.daily.diary': 'Cuestionario de Salud Diario',
    'activity.anytime': 'Cualquier momento',
    'activity.daily.diary.details': 'Registre sus síntomas diarios, medicamentos tomados y cualquier efecto secundario',
    'activity.mobile.location': 'En línea - Aplicación móvil o portal web',
    'activity.survey.completed': 'Cuestionario completado exitosamente! Gracias por su participación.',
    'activity.pdf.export': 'Exportación PDF iniciada - las respuestas del cuestionario se descargarían como un documento seguro y sin identificación.',
    'activity.view.details': 'Ver Detalles',
    'activity.important.notes': 'Notas Importantes',
    
    // Calendar
    'calendar.view.full': 'Ver Calendario Completo',
    
    // Questionnaires
    'questionnaire.your.surveys': 'Sus Cuestionarios',
    'questionnaire.view.all': 'Ver Todos los Cuestionarios',
    'questionnaire.pending': 'Pendientes',
    'questionnaire.completed': 'Completadas',
    'questionnaire.completion.rate': 'Tasa de Finalización',
    'questionnaire.thanks.completing': '¡Gracias por completar el cuestionario de hoy!',
    'questionnaire.quick.survey': 'Cuestionario rápido de 5 minutos sobre sus síntomas diarios',
    'questionnaire.complete.now': 'Completar Ahora',
    
    // Questionnaire Form
    'questionnaire.form.question': 'Pregunta',
    'questionnaire.form.of': 'de',
    'questionnaire.form.complete': 'Completar',
    'questionnaire.form.completed': '¡Cuestionario Completado!',
    'questionnaire.form.thank.you': 'Gracias por completar',
    'questionnaire.form.responses.saved': 'Sus respuestas han sido guardadas.',
    'questionnaire.form.close': 'Cerrar',
    'questionnaire.form.previous': 'Anterior',
    'questionnaire.form.next': 'Siguiente',
    'questionnaire.form.enter.response': 'Ingrese su respuesta...',
    'questionnaire.form.not.at.all': 'Para nada',
    'questionnaire.form.extremely': 'Extremadamente',
    'questionnaire.form.selected': 'Seleccionado',
    
    // Questionnaire List
    'questionnaire.list.title': 'Cuestionarios',
    'questionnaire.list.completed.count': 'Completados',
    'questionnaire.list.in.progress.count': 'En Progreso',
    'questionnaire.list.pending.count': 'Pendientes',
    'questionnaire.list.overdue.count': 'Vencidos',
    'questionnaire.list.due.date': 'Fecha de Vencimiento',
    'questionnaire.list.completed.date': 'Completado',
    'questionnaire.list.score': 'Puntuación',
    'questionnaire.list.progress': 'Progreso',
    'questionnaire.list.view.responses': 'Ver Respuestas',
    'questionnaire.list.no.responses': 'Aún no se han registrado respuestas.',
    'questionnaire.list.responses.for': 'Respuestas para',
    'questionnaire.list.data.privacy': 'Privacidad de Datos',
    'questionnaire.list.privacy.note': 'Todas las respuestas de cuestionarios están encriptadas y almacenadas de forma segura. El acceso está limitado al personal autorizado del estudio y cumple con las regulaciones HIPAA.',
    
    // Questionnaire Status
    'questionnaire.status.completed': 'Completado',
    'questionnaire.status.in.progress': 'En Progreso', 
    'questionnaire.status.pending': 'Pendiente',
    'questionnaire.status.overdue': 'Vencido',
    
    // Sample Questionnaires
    'questionnaire.daily.symptom.diary': 'Diario de Síntomas Diarios',
    'questionnaire.weekly.qol.assessment': 'Evaluación Semanal de Calidad de Vida',
    'questionnaire.medication.adherence': 'Encuesta de Adherencia a Medicamentos',
    'questionnaire.monthly.health': 'Encuesta Mensual de Salud',
    'questionnaire.side.effects': 'Evaluación de Efectos Secundarios',
    
    // Questionnaire Questions
    'questionnaire.question.symptoms.today': '¿Qué síntomas experimentó hoy?',
    'questionnaire.question.symptom.severity': 'En una escala del 1-10, ¿cómo calificaría la severidad general de sus síntomas hoy?',
    'questionnaire.question.medication.taken': '¿Tomó su medicamento del estudio hoy?',
    'questionnaire.question.physical.health': '¿Cómo calificaría su salud física esta semana?',
    'questionnaire.question.emotional.wellbeing': '¿Cómo calificaría su bienestar emocional esta semana?',
    'questionnaire.question.daily.activities': '¿Cuánto limitaron los problemas de salud sus actividades diarias?',
    'questionnaire.question.sleep.quality': '¿Cómo calificaría la calidad de su sueño esta semana?',
    'questionnaire.question.doses.missed': '¿Cuántas dosis perdió esta semana?',
    'questionnaire.question.reasons.missed': 'Si perdió dosis, ¿cuáles fueron las razones?',
    'questionnaire.question.overall.health': '¿Cómo calificaría su salud general?',
    
    // Questionnaire Options
    'questionnaire.option.headache': 'Dolor de cabeza',
    'questionnaire.option.nausea': 'Náuseas',
    'questionnaire.option.fatigue': 'Fatiga',
    'questionnaire.option.dizziness': 'Mareos',
    'questionnaire.option.loss.appetite': 'Pérdida de apetito',
    'questionnaire.option.none': 'Ninguno',
    'questionnaire.option.yes.prescribed': 'Sí, según lo prescrito',
    'questionnaire.option.yes.missed.dose': 'Sí, pero perdí una dosis',
    'questionnaire.option.no.forgot': 'No, se me olvidó',
    'questionnaire.option.no.side.effects': 'No, efectos secundarios',
    'questionnaire.option.not.at.all': 'Para nada',
    'questionnaire.option.little.bit': 'Un poco',
    'questionnaire.option.moderately': 'Moderadamente',
    'questionnaire.option.quite.bit': 'Bastante',
    'questionnaire.option.extremely': 'Extremadamente',
    'questionnaire.option.forgot': 'Se me olvidó',
    'questionnaire.option.side.effects': 'Efectos secundarios',
    'questionnaire.option.felt.better': 'Me sentía mejor',
    'questionnaire.option.too.busy': 'Muy ocupado',
    'questionnaire.option.cost': 'Costo',
    'questionnaire.option.other': 'Otro',
    
    // eConsent Signature
    'econsent.signature.canvas.instruction': 'Por favor firme en el recuadro de abajo',
    'econsent.signature.clear.confirm': '¿Está seguro de que desea borrar su firma?',
    'econsent.signature.invalid': 'Por favor proporcione una firma válida',
    'econsent.signature.success': 'Documento firmado exitosamente',
    'econsent.signature.error': 'Error al firmar el documento. Por favor intente de nuevo.',
    'econsent.previous.signed': 'ICFs Firmados Anteriormente',
    'econsent.optional.available': 'ICFs Opcionales Disponibles',
    'econsent.audio.playback': 'Controles de Reproducción de Audio',
    'econsent.pharmacokinetics': 'Farmacocinética (FC)',
    'econsent.biomarkers': 'Biomarcadores',
    'econsent.pregnant.partner': 'Pareja Embarazada',
    'econsent.last.updated': 'Última Actualización',
    'econsent.version': 'Versión',
    'econsent.sign.button': 'Firmar',
    'econsent.playback.speed': 'Velocidad de Reproducción',
    'econsent.normal.speed': 'Normal',
    'econsent.slow.speed': 'Lento',
    'econsent.fast.speed': 'Rápido',
    
    // Visits
    'visits.site.visits': 'Visitas',
    'visits.baseline.completed': 'Visita Basal - Completada',
    'visits.baseline.procedures': 'Extracción de sangre, signos vitales, cuestionarios completados',
    'visits.notes': 'Notas de la Visita',
    'visits.baseline.notes': 'Todos los procedimientos completados exitosamente. Presión arterial ligeramente elevada, se monitoreará en la próxima visita. El paciente no reportó eventos adversos.',
    'visits.week4.scheduled': 'Visita Semana 4 - Programada',
    'visits.week4.procedures': 'Extracción de sangre, evaluación de seguridad, cuestionarios',
    'visits.preparation.notes': 'Notas de Preparación',
    'visits.week4.notes': 'Por favor ayune durante 12 horas antes de la visita. Traiga su diario de medicamentos y cualquier pregunta que pueda tener.',
    
    // Profile
    'profile.view.settings': 'Ver Perfil y Configuración',
    'profile.export.pdf': 'Exportar Mis Respuestas (PDF)',
    'profile.privacy.security': 'Privacidad y Seguridad',
    'profile.privacy.description': 'Sus datos están encriptados y protegidos según los estándares HIPAA. Todas las respuestas son desidentificadas para el análisis.',
    
    // Participant Details
    'details.title': 'Detalles del Participante',
    'details.alerts': 'Alertas',
    'details.visit.overdue': 'Visita vencida',
    'details.monthly.assessment': 'Pendiente de evaluación mensual',
    'details.basic.info': 'Información Básica',
    'details.demographics': 'Demografía',
    'details.icf.title': 'Consentimiento Informado (ICF)',
    'details.icf.version': 'Versión ICF',
    'details.icf.signed.date': 'Fecha de Firma',
    'details.icf.status': 'Estado',
    'details.icf.action.required': 'Acción Requerida',
    'details.icf.updated.schedule': 'ICF ha sido actualizado a v2.1. Por favor programe una visita de re-consentimiento.',
    'details.study.progress': 'Progreso del Estudio',
    'details.recent.activity': 'Actividad Reciente',
    'details.upcoming.events': 'Eventos Próximos',
    'details.age': 'Edad',
    'details.gender': 'Género',
    'details.ethnicity': 'Etnia',
    
    // Settings
    'settings.title': 'Configuración',
    'settings.subtitle': 'Gestiona tus preferencias y cuenta',
    'settings.back': 'Atrás',
    'settings.language.preferences': 'Preferencias de Idioma',
    'settings.display.language': 'Idioma de Visualización',
    'settings.language.note': 'Los cambios se aplicarán después de actualizar la página',
    'settings.tutorial.section': 'Tutorial',
    'settings.start.tutorial': 'Iniciar Tutorial',
    'settings.tutorial.description': 'Aprende a usar la aplicación con tours guiados',
    'settings.account.actions': 'Acciones de Cuenta',
    'settings.sign.out': 'Cerrar Sesión',
    'settings.sign.out.note': 'Serás redirigido a la página de inicio de sesión',
    
    // Onboarding
    'onboarding.action.required': 'Acción Requerida',
    'onboarding.previous': 'Anterior',
    'onboarding.next': 'Siguiente',
    'onboarding.skip': 'Saltar Tutorial',
    'onboarding.try.it': 'Probarlo',
    'onboarding.finish': 'Terminar',
    
    // Participant Onboarding
    'onboarding.participant.welcome.title': 'Bienvenido a tu Portal de Estudio',
    'onboarding.participant.welcome.description': 'Este es tu panel personal donde puedes seguir el progreso de tu estudio y el estado de finalización.',
    'onboarding.participant.progress.title': 'Seguimiento del Progreso del Estudio',
    'onboarding.participant.progress.description': 'Monitorea tu porcentaje general de finalización del estudio y los días restantes.',
    'onboarding.participant.schedule.title': 'Tu Agenda',
    'onboarding.participant.schedule.description': 'Ve próximas citas, cuestionarios y visitas al sitio. Haz clic para explorar tu calendario.',
    'onboarding.participant.schedule.action': 'Haz clic en la pestaña Agenda para ver tus actividades próximas',
    'onboarding.participant.questionnaires.title': 'Cuestionarios',
    'onboarding.participant.questionnaires.description': 'Completa encuestas requeridas y rastrea tu tasa de finalización de respuestas.',
    'onboarding.participant.questionnaires.action': 'Haz clic en Cuestionarios para ver encuestas pendientes',
    'onboarding.participant.econsent.title': 'Consentimiento Electrónico',
    'onboarding.participant.econsent.description': 'Revisa y gestiona tus documentos de consentimiento informado y firmas.',
    'onboarding.participant.visits.title': 'Visitas al Sitio',
    'onboarding.participant.visits.description': 'Rastrea tus visitas al sitio completadas y próximas con información detallada.',
    'onboarding.participant.contact.title': 'Información de Contacto',
    'onboarding.participant.contact.description': 'Accede a detalles de contacto de tu equipo de estudio, contactos de emergencia y números importantes.',
    
    // Investigator Onboarding
    'onboarding.investigator.metrics.title': 'Resumen de Métricas del Estudio',
    'onboarding.investigator.metrics.description': 'Monitorea métricas clave del estudio incluyendo participantes inscritos, revisiones pendientes y eventos adversos.',
    'onboarding.investigator.participants.title': 'Gestión de Participantes',
    'onboarding.investigator.participants.description': 'Accede a la lista integral de participantes con estado de inscripción, cumplimiento y horarios de visitas.',
    'onboarding.investigator.calendar.title': 'Gestión de Calendario',
    'onboarding.investigator.calendar.description': 'Programa y gestiona visitas de participantes, citas y hitos del estudio.',
    'onboarding.investigator.barcode.title': 'Escáner de Códigos de Barras',
    'onboarding.investigator.barcode.description': 'Identifica rápidamente participantes y accede a su información usando escaneo de códigos de barras.',
    'onboarding.investigator.fhir.title': 'Interoperabilidad FHIR',
    'onboarding.investigator.fhir.description': 'Exporta datos del estudio en formato FHIR para integración con sistemas de salud.',
    'onboarding.investigator.progress.title': 'Seguimiento de Cumplimiento',
    'onboarding.investigator.progress.description': 'Monitorea el progreso del estudio, cumplimiento del diario y tasas de finalización de visitas.',
    
    // CRO/Sponsor Onboarding
    'onboarding.cro.overview.title': 'Resumen del Portafolio',
    'onboarding.cro.overview.description': 'Obtén una vista de alto nivel de todos los estudios activos, sitios de investigación y métricas de participantes.',
    'onboarding.cro.selector.title': 'Selección de Estudio',
    'onboarding.cro.selector.description': 'Elige en qué estudio enfocarte para análisis detallado y gestión.',
    'onboarding.cro.tabs.title': 'Navegación Principal',
    'onboarding.cro.tabs.description': 'Accede a diferentes secciones: detalles del estudio, cuestionarios, horarios, participantes y reportes.',
    'onboarding.cro.questionnaires.title': 'Analíticas de Cuestionarios',
    'onboarding.cro.questionnaires.description': 'Analiza tasas de respuesta, revisiones de calidad y validación de datos en todos los sitios.',
    'onboarding.cro.questionnaires.action': 'Haz clic en Cuestionarios para explorar analíticas',
    'onboarding.cro.reports.title': 'Reportes y Descargas',
    'onboarding.cro.reports.description': 'Genera y descarga varios reportes para envíos regulatorios y análisis.',
    'onboarding.cro.reports.action': 'Haz clic en Reportes para ver descargas disponibles',
    
    // eConsent
    'econsent.title': 'Consentimiento',
    'econsent.subtitle': 'Revisa y firma tu documento de consentimiento informado',
    'econsent.document.title': 'Formulario de Consentimiento Informado',
    'econsent.audio.play': 'Reproducir Audio',
    'econsent.audio.pause': 'Pausar Audio',
    'econsent.audio.stop': 'Detener Audio',
    'econsent.search.placeholder': 'Buscar en documento...',
    'econsent.search.results': 'Resultados de Búsqueda',
    'econsent.search.no.results': 'No se encontraron resultados',
    'econsent.signature.required': 'Firma Electrónica Requerida',
    'econsent.signature.full.name': 'Nombre Completo',
    'econsent.signature.date': 'Fecha',
    'econsent.signature.agree': 'Acepto participar en este estudio',
    'econsent.signature.sign': 'Firmar Documento',
    'econsent.signature.clear': 'Limpiar Firma',
    'econsent.signature.complete': 'Consentimiento Firmado Exitosamente',
    'econsent.download.pdf': 'Descargar PDF',
    'econsent.view.signed': 'Ver Documento Firmado',
    'econsent.history': 'Historial',
    'econsent.status.signed': 'Firmado',
    'econsent.status.superseded': 'Reemplazado',
    'econsent.status.pending': 'Pendiente',
    
    // Consent Dashboard (Spanish)
    'consent.dashboard.title': 'Gestión de Consentimientos',
    'consent.dashboard.pending': 'Firmas Pendientes',
    'consent.dashboard.urgent': 'Urgente',
    'consent.dashboard.high.priority': 'Alta Prioridad',
    'consent.dashboard.normal': 'Normal',
    'consent.dashboard.avg.days': 'Días Promedio Pendientes',
    'consent.dashboard.search.placeholder': 'Buscar participantes o IDs de sujeto...',
    'consent.dashboard.no.results': 'No se encontraron firmas coincidentes',
    'consent.dashboard.no.pending': 'No hay firmas pendientes',
    'consent.dashboard.signed.on': 'Firmado el',
    'consent.dashboard.days.pending': 'días pendientes',
    'consent.dashboard.view': 'Ver',
    'consent.dashboard.sign': 'Firmar',
    'consent.dashboard.reauth.title': 'Re-autenticarse para Firmar Consentimiento',
    'consent.dashboard.reauth.description': 'Por motivos de seguridad y cumplimiento, vuelva a introducir su contraseña para firmar electrónicamente este formulario de consentimiento.',

    // Consent Types (Spanish)
    'consent.type.main.icf': 'Consentimiento Informado Principal',
    'consent.type.pharmacokinetics': 'Estudio de Farmacocinética',
    'consent.type.biomarkers': 'Análisis de Biomarcadores',
    'consent.type.pregnant.partner': 'Consentimiento de Pareja Embarazada',
    
    // Common
    'common.welcome': 'Bienvenido',
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.close': 'Cerrar',
    'common.continue': 'Continuar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.completed': 'Completado',
    'common.due.today': 'Vence Hoy',
    'common.complete': 'Completar',
    'common.pending': 'Pendiente',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.details': 'Detalles',
    'common.milestone': 'Hito',
    'common.regulatory': 'Regulatorio',
    
    // Login and Authentication (Spanish)
    'login.title': 'Iniciar Sesión',
    'login.subtitle': 'Inicia sesión para acceder a tu cuenta',
    'login.email': 'Correo Electrónico',
    'login.email.placeholder': 'Ingresa tu correo electrónico',
    'login.password': 'Contraseña',
    'login.password.placeholder': 'Ingresa tu contraseña',
    'login.role.select': 'Selecciona tu rol',
    'login.role.selection.subtitle': 'Selecciona tu rol para continuar',
    'login.button': 'Iniciar Sesión',
    'login.back': 'Volver a Selección de Rol',
    'login.help': '¿No tienes acceso? Contacta a tu administrador',
    'login.roles.participant': 'Participante',
    'login.roles.investigator': 'Sitio',
    'login.roles.cro-sponsor': 'CRO/Patrocinador',
    'login.roles.participant.description': 'Accede a tu portal de participación en estudios',
    'login.roles.investigator.description': 'Gestiona y monitorea estudios clínicos',
    'login.roles.cro-sponsor.description': 'Supervisa y administra programas de investigación',
    
    // Status values
    'status.completed': 'completado',
    'status.scheduled': 'programado',
    'status.overdue': 'vencido',
    
    // Activity types
    'activity.visit': 'visita',
    'activity.questionnaire': 'cuestionario',
    'activity.call': 'llamada',
    'activity.diary': 'diario',
    'activity.assessment': 'evaluación',
    'activity.lab': 'laboratorio',
    'activity.meeting': 'reunión',
    
    // Study Selector
    'study.selector.investigator.title': 'Seleccionar Estudio - Investigador del Sitio',
    'study.selector.cro.title': 'Seleccionar Estudio - CRO/Patrocinador',
    'study.selector.subtitle': 'Elige el estudio al que quieres acceder',
    'study.sites': 'sitios',
    'study.participants': 'participantes',
    
    // CRO/Sponsor Dashboard
    'cro.portfolio.overview': 'Resumen del Portafolio',
    'cro.global.research.ops': 'Panel de Operaciones de Investigación Global',
    'cro.active.studies': 'Estudios activos',
    'cro.research.sites': 'Sitios de investigación',
    'cro.total.participants': 'Participantes totales',
    'cro.compliance.rate': 'Tasa de cumplimiento',
    'cro.study.details': 'Detalles del Estudio',
    'cro.questionnaires': 'Cuestionarios',
    'cro.schedule': 'Cronograma',
    'cro.participants': 'Participantes',
    'cro.reports': 'Reportes',
    'cro.select.study': 'Seleccionar un Estudio',
    'cro.performance.metrics': 'Métricas de Rendimiento',
    'cro.budget.utilization': 'Utilización del Presupuesto',
    'cro.timeline.progress': 'Progreso del Cronograma',
    'cro.spent': 'Gastado',
    'cro.completion': 'Finalización',
    'cro.enrollment.tracker': 'Seguimiento de Inscripción',
    'cro.current': 'Actual',
    'cro.target': 'Objetivo',
    'cro.retention.rate': 'Tasa de Retención',
    'cro.compliance.score': 'Puntuación de Cumplimiento',
    'cro.set.favorite': 'Marcar como Favorito',
    'cro.remove.favorite': 'Quitar Favorito',
    'cro.favorite.study': 'Estudio Favorito',
    'cro.milestone.schedule': 'Hitos y Cronograma del Estudio',
    'cro.key.milestones': 'Hitos Clave del Estudio',
    'cro.milestone.completed': 'Completado',
    'cro.milestone.pending': 'Pendiente',
    'cro.questionnaire.analytics': 'Análisis de Cuestionarios',
    'cro.response.rates': 'Tasas de Respuesta',
    'cro.quality.reviews': 'Revisiones de Calidad',
    'cro.data.validation': 'Problemas de Validación de Datos',
    'cro.daily.symptom': 'Síntomas Diarios',
    'cro.weekly.qol': 'Calidad de Vida Semanal',
    'cro.monthly.health': 'Salud Mensual',
    'cro.download.reports': 'Descargar Reportes',
    'cro.site.users.report': 'Reporte de Usuarios del Sitio',
    'cro.site.users.report.description': 'Reporte detallado de actividad de investigadores y personal del sitio',
    'cro.questionnaire.report': 'Reporte de Cuestionarios',
    'cro.questionnaire.report.description': 'Respuestas completas de cuestionarios y datos de cumplimiento',
    'cro.milestones.report': 'Reporte de Hitos',
    'cro.milestones.report.description': 'Seguimiento de cronogramas y análisis de logros de hitos',
    'cro.interoperability': 'Módulo de Interoperabilidad',
    'cro.export.fhir': 'Exportar Datos FHIR',
    'cro.export.fhir.description': 'Exportar datos del estudio en formato FHIR R4 para envío regulatorio',
    'cro.export.hl7': 'Exportar Mensajes HL7',
    'cro.export.hl7.description': 'Generar mensajes HL7 para integración de sistemas de salud',
    'cro.validate.cdisc': 'Validar Estándares CDISC',
    'cro.validate.cdisc.description': 'Validar contra el Modelo de Tabulación de Datos de Estudio CDISC',
    'cro.advanced.analytics': 'Análisis Avanzado',
    
    // Study Details Attributes
    'study.protocol': 'Protocolo',
    'study.phase': 'Fase',
    'study.sponsor': 'Patrocinador',
    'study.sites.count': 'Sitios',
    'study.participants.count': 'Participantes',
    'study.status': 'Estado',
    'study.recent.alerts': 'Alertas Recientes',
    
    // ClinicalTrials.gov Status Values (Spanish)
    'study.status.not.yet.recruiting': 'Aún no reclutando',
    'study.status.recruiting': 'Reclutando',
    'study.status.enrolling.by.invitation': 'Inscribiendo por invitación',
    'study.status.active.not.recruiting': 'Activo, no reclutando',
    'study.status.suspended': 'Suspendido',
    'study.status.terminated': 'Terminado',
    'study.status.completed': 'Completado',
    'study.status.withdrawn': 'Retirado',
    'study.status.unknown': 'Estado desconocido',
    
    // Recruitment and Site Metrics (Spanish)
    'study.recruitment.metrics': 'Métricas de Reclutamiento',
    'study.site.metrics': 'Métricas de Apertura de Sitios',
    'study.recruitment.rate': 'Tasa de Reclutamiento',
    'study.patients.per.month': 'pacientes/mes',
    'study.sites.opened': 'Sitios Abiertos',
    'study.sites.planned': 'Sitios Planificados',
    'study.site.activation.rate': 'Tasa de Activación de Sitios',
    'study.days.to.activate': 'días para activar',
    
    // Alert Messages (Spanish)
    'alert.cardiology.milestone': 'Hito de cardiología logrado antes de lo previsto',
    'alert.interim.analysis': 'Análisis intermedio de PARADIGM-CV completado',
    'alert.enrollment.target': 'Meta de inscripción alcanzada para Q4',
    'alert.safety.review': 'Revisión mensual de seguridad completada',
    'alert.site.activation': 'Nuevo sitio activado en Boston Medical Center',
    'alert.data.validation': 'Problemas de validación de datos resueltos',
    'alert.regulatory.submission': 'Envío regulatorio preparado',
    'alert.biomarker.analysis': 'Hito de análisis de biomarcadores completado'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('language') || 'spanish';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.english] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
