// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwixpiyptdykphqqfyru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3aXhwaXlwdGR5a3BocXFmeXJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDcyMDQsImV4cCI6MjA2NzA4MzIwNH0.giE_0Mwzvs_TZHdqY1Q13WOc68GaqIyh18F445oefsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});